### ISSUE TITLE
Get tests working on Travis / Linux

### ISSUE THREAD

**Issue by dougbu** [aspnet/Entropy#102]
Entropy builds have been erroring or failing consistently on Travis for a while. Looks like the last successful Travis run was 16 days ago. (Admittedly, that span may include runs where Linux succeeded but OS X failed.)

The current unique issue appears to be a failure while executing `dotnet publish`. It's likely some of the recent infrastructure changes have either not yet been applied in this repo or been miss-applied.

See failures in https://travis-ci.org/aspnet/Entropy/jobs/111584356 for example.

Problems here may relate to aspnet/KestrelHttpServer#654

**Comment by muratg** [comment]
@JunTaoLuo Could you look into this?  

@victorhurdugaci in case he has any ideas.

**Comment by JunTaoLuo** [comment]
There are several issues here

- [ ] Self host deployer not using the correct extensions, should be fixed by https://github.com/aspnet/Hosting/commit/0d737d5eb81b04778304c9842d1352ff4439ab86
- [ ] Hangs
- [ ] Localization.Web is not published correctly

**Comment by cesarbs** [comment]
Some tests failures on OS X on CoreCLR CI runs: http://aspnetci/viewLog.html?buildId=76003&buildTypeId=XPlat_Mac_MacUniverseCoreCLR&tab=buildLog#_state=24330&focus=32064

**Comment by JunTaoLuo** [comment]
The CI machine did not have bower installed and could not publish. Probably gulp needs to be installed as well. This is similar to https://github.com/aspnet/Entropy/pull/104. Maybe we should add something in Korebuild to guarantee that these utils are always installed.

**Comment by JunTaoLuo** [comment]
Tests passing on Travis and locally. Will continue to monitor on CI.

**Comment by dougbu** [comment]
> The CI machine did not have bower installed and could not publish

@JunTaoLuo huh? Last I looked, the `.shade` files using Bower all detected its installation status and installed it (and `npm`) locally if necessary. The main issue are that Node.js must be installed on non-Windows systems and the poor performance of doing local Bower and Gulp installations repeatedly.

If some `.shade` code uses one of these commands w/o first confirming it's installed, file a bug or fix it.

**Comment by JunTaoLuo** [comment]
@dougbu It's not the `.shade` files that invoke bower and gulp. Some sample projects have a bower/gulp step in their `project.json`. The tests in entropy publishes the samples and thus invokes bower and gulp. I have also found another problem for agent 10 which is that the installed bower and gulp were not on the PATH. After resolving that, the tests are running fine.

**Comment by dougbu** [comment]
> Some sample projects have a bower/gulp step in their `project.json`.

That's an antipattern. `project.json` files in our repos should not contain such commands. We want the repos to be bootstrappable without manual steps. Just download the .zip or clone the repo and run `.\build.ps1` or `./build.sh`.

As a minor detail, we're likely running Bower and or Gulp twice for each of these projects. Once when the `.shade` file detects the relevant configuration files; again during the `publish`.

**Comment by JunTaoLuo** [comment]
I'm a little confused. Our samples do not have their own repos and they do not have any build scripts. The project I was referring to was https://github.com/aspnet/Entropy/blob/dev/samples/Localization.StarterWeb/project.json. This looks like a localized version of StarterWeb project. It carries over the gulp/bower functionalities from the generated sample but I believe that's the point. When we publish this sample in our tests we want to emulate the real user experience.

From what you have suggested, I think there are two options. One, remove the use of gulp/bower in our sample projects, though I believe this reduces our test coverage slightly. Two, update our build scripts to scan the sample project and see if the tools are used and install them as needed. 

I don't think either are really worth the effort as the only thing we need to do is install bower/gulp globally once on the CI agent. Unless we plan to dynamically generate OSX and Linux agents, I don't think this is an issue. And even then, installing the tools can be part of a setup script.

Please let me know if I'm missing something here.

**Comment by dougbu** [comment]
> they do not have any build scripts

All of our repos have build scripts. Have a look at https://github.com/aspnet/KoreBuild/blob/dev/build/shade/_k-standard-goals.shade#L40-L56

> Two, update our build scripts to scan the sample project and see if the tools are used and install them as needed.

Scripts don't currently support Gulp but all NPM, Bower and Grunt tasks run automatically.

> I'm missing something here.

The third option is to add Gulp support to `_k-standard-goals.shade` and remove `"scripts"` from the `project.json` file. Then Entropy will work w/o users having to perform additional installations. Global installation would remain an option to improve build performance.

**Comment by JunTaoLuo** [comment]
> All of our repos have build scripts.

Yes, I know each **repo** has build scripts. What I meant was each **sample** doesn't have their individual build scripts. We just run them or test them.

> Scripts don't currently support Gulp

Exactly, and we need additional work to add support for it. I don't think this case pops up often enough though.

> add Gulp support to _k-standard-goals.shade

Sure, I can open an issue to track it. The entropy is a proving ground for different samples. It's there to illustrate more peculiar use cases and we test them to make sure we don't regress. It seems like a lot of work just to avoid users having to install two tools before running the functional tests. In fact, I would imagine most users would run the samples directly which do not require these tools which are run only during publish.
