### ISSUE TITLE
Update the Localization.StarterWeb sample to show localization of views

### ISSUE THREAD

**Issue by kichalla** [aspnet/Entropy#127]
I was trying to look for a sample where we show localization of views using different localization view formats. I see that Localization.StarterWeb adds the necessary services but doesn't seem to have any views actually.

https://github.com/aspnet/Entropy/blob/dev/samples/Localization.StarterWeb/Startup.cs#L57

**Comment by Eilon** [comment]
@ryanbrandenburg I assigned PR https://github.com/aspnet/Entropy/pull/134 from @hishamco to you for this.

**Comment by ryanbrandenburg** [comment]
This was closed in be24723.
