### ISSUE TITLE
Localization.StarterWeb test failures

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/Entropy#129]
Still investigating but just going to list what I have found so far.

The failure I'm seeing on the CI is at http://aspnetci/viewLog.html?buildId=100911&buildTypeId=Lite_UniverseTest&tab=buildLog#_focus=64532 which is caused by:
```
info: Localization.StarterWeb:Kestrel:Clr:x64[0]
      System.InvalidOperationException: Can not find assembly file Microsoft.DotNet.Cli.Utils.dll at 'C:\Users\johluo\AppData\Local\Temp\058a9647-0c7a-4181-82f3-158ee5541928\refs,C:\Users\johluo\AppData\Local\Temp\058a9647-0c7a-4181-82f3-158ee5541928\'
info: Localization.StarterWeb:Kestrel:Clr:x64[0]
         at Microsoft.Extensions.DependencyModel.Resolution.AppBaseCompilationAssemblyResolver.TryResolveAssemblyPaths(CompilationLibrary library, List`1 assemblies)
info: Localization.StarterWeb:Kestrel:Clr:x64[0]
         at Microsoft.Extensions.DependencyModel.Resolution.CompositeCompilationAssemblyResolver.TryResolveAssemblyPaths(CompilationLibrary library, List`1 assemblies)
info: Localization.StarterWeb:Kestrel:Clr:x64[0]
         at Microsoft.Extensions.DependencyModel.CompilationLibrary.ResolveReferencePaths()
info: Localization.StarterWeb:Kestrel:Clr:x64[0]
         at Microsoft.AspNetCore.Mvc.Razor.Compilation.MetadataReferenceFeatureProvider.PopulateFeature(IEnumerable`1 parts, MetadataReferenceFeature feature)
info: Localization.StarterWeb:Kestrel:Clr:x64[0]
         at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager.PopulateFeature[TFeature](TFeature feature)
```
This seems to have started after the changes in https://github.com/aspnet/Mvc/issues/4498. The reason this error occurs is that for the `net451 TFM`, while the assembly `Microsoft.DotNet.Cli.Utils.dll` appears in the build output of the project, it does not show up in the published output. What I'm curious about is why this dotnet cli assembly is being loaded even in full framework and whether this is a publish issue or an issue with how Razor is loading the assemblies. 

cc @cesarbs @pranavkm

**Comment by JunTaoLuo** [comment]
looks like a cli issue, @pakrym will be filing an issue in cli. Will try to find a work around or disable the tests.

**Comment by JunTaoLuo** [comment]
Workaround checked in, will keep this issue open to revert the change when cli issue is fixed.

**Comment by muratg** [comment]
Putting this 1.0.1 to track the change to revert this.

**Comment by muratg** [comment]
@JunTaoLuo what's the CLI bug? Could you link to that?

@piotrpMSFT FYI. We'd need the CLI fix for this one.

**Comment by JunTaoLuo** [comment]
@pakrym says he's fixing it.

**Comment by pakrym** [comment]
https://github.com/dotnet/cli/issues/3252 is the CLI issue

**Comment by pakrym** [comment]
Reverted workaround: https://github.com/aspnet/Entropy/commit/b118b16f87d26cae9ac30710154417f867f36d64
