### ISSUE TITLE
Add a sample for Ajax + Antiforgery + Auth

### ISSUE THREAD

**Issue by kichalla** [aspnet/Entropy#130]
We currently have a sample in Antiforgery repo for showing Ajax + Antiforgery.

Based on the following issue, it appears it would be nice to have a sample which adds Auth also.

https://github.com/aspnet/Antiforgery/issues/83

**Comment by ryanbrandenburg** [comment]
I think [this](https://github.com/ryanbrandenburg/AjaxAntiForgeryValidation) will be a good start on this work, but I'll need to clean it up some more and turn it into a "real" scenario.
