### ISSUE TITLE
Re-enable CLR tests on Linux/Mac

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/Entropy#136]
Currently disabled due to corefx issue: https://github.com/dotnet/corefx/issues/9012. Need to revert https://github.com/aspnet/Entropy/commit/a8df61bf46d33704c7fca0bee4d47de817bcc4b8 once it is resolved.

**Comment by JunTaoLuo** [comment]
Moving to 1.0.1 since the related corefx issue got punted to 1.1.0. cc @muratg

**Comment by Eilon** [comment]
@JunTaoLuo can we re-enable this test now? Looks like https://github.com/dotnet/corefx/issues/9012 got moved to 1.2.0, so do we want to push on that to get fixed sooner? If not, let's move this bug to 1.2.0.

**Comment by JunTaoLuo** [comment]
Yup, just tried it again the same issue exists so let's move this. Since I don't see 1.2.0, I'll move it to backlog. In fact, I'm not sure how much testing on Mono we plan to have in the future?

**Comment by Eilon** [comment]
Was this an issue just on Mono?

**Comment by JunTaoLuo** [comment]
Correct, we disabled tests that targeted net451 on *nix due to the original issue.

**Comment by Eilon** [comment]
Ok then closing this because we're not concerned about Mono support in this case.
