### ISSUE TITLE
Some samples have incorrect dependencies

### ISSUE THREAD

**Issue by javiercn** [aspnet/Entropy#140]
Errors in C:\work\Universe\Entropy\samples\Localization.StarterWeb\project.json
    Package Microsoft.Extensions.Configuration.FileProviderExtensions 1.0.0-rc1-final is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). **Package Microsoft.Extensions.Configuration.FileProviderExten
sions 1.0.0-rc1-final supports**:
      - dotnet5.4 (.NETPlatform,Version=v5.4)
      - net451 (.NETFramework,Version=v4.5.1)
      - netcore50 (.NETCore,Version=v5.0)
    One or more packages are incompatible with .NETCoreApp,Version=v1.0.

Errors in C:\work\Universe\Entropy\samples\MusicStore.Spa\project.json
    **Package AutoMapper 4.0.0-alpha1 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package AutoMapper 4.0.0-alpha1 supports**:
      - dnx46 (DNX,Version=v4.6)
      - dnxcore50 (DNXCore,Version=v5.0)
      - monoandroid (MonoAndroid,Version=v0.0)
      - monotouch (MonoTouch,Version=v0.0)
      - net45 (.NETFramework,Version=v4.5)
      - portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)
      - sl5 (Silverlight,Version=v5.0)
      - win (Windows,Version=v0.0)
      - wp8 (WindowsPhone,Version=v8.0)
      - wpa81 (WindowsPhoneApp,Version=v8.1)
      - xamarinios10 (Xamarin.iOS,Version=v1.0)
    One or more packages are incompatible with .NETCoreApp,Version=v1.0.

Errors in C:\work\Universe\Entropy\samples\Mvc.FileUpload\project.json
    **Package Newtonsoft.Json 7.0.1 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Newtonsoft.Json 7.0.1 supports**:
      - net20 (.NETFramework,Version=v2.0)
      - net35 (.NETFramework,Version=v3.5)
      - net40 (.NETFramework,Version=v4.0)
      - net45 (.NETFramework,Version=v4.5)
      - portable-dnxcore50+net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=net45+wp80+win8+wpa81+dnxcore50)
      - portable-net40+sl5+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile328)
    One or more packages are incompatible with .NETCoreApp,Version=v1.0.

**Comment by muratg** [comment]
@JunTaoLuo Could you clean this up?
