### ISSUE TITLE
[Dependency Fail Information] Unhandled Exception: System.ArgumentNullException: Value cannot be null. Parameter name: assemblyName

### ISSUE THREAD

**Issue by ChristopherJdL** [aspnet/Entropy#151]
Hello aspnet,

When we run the project present in the following folder : "Entropy/samples/Mvc.RenderViewToString/"
We cannot avoid the exception that we see here:
![image](https://cloud.githubusercontent.com/assets/14253146/16736588/e3fd7424-478d-11e6-8de5-662b30257544.png)
This is the result of dotnet core failing to instantiate the needed dependencies for the RazorViewToStringRenderer.
Since we took this code as an example to build our own Razor view renderer, we experienced the same exception when upgrading to dotnet core.
Do you manage to make this Mvc.RenderViewToString project run properly ?

Thank you for your returns.

**Comment by adrien-constant** [comment]
Fixed by the last commit a few hours ago : 
https://github.com/aspnet/Entropy/commit/02c2b8d2adf599d9263a957388d5b8fd62e5f8e8

**Comment by muratg** [comment]
:+1:
