### ISSUE TITLE
Clean up functional tests 

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/Entropy#156]
The functional tests are a bit warty and have lots of repetitive code and functions with lots of arguments. Simplify and de-duplicate the tests and their underlying code. The Mvc functional tests would likely make a good guide.

**Comment by muratg** [comment]
@ryanbrandenburg do you have time to take this?

**Comment by ryanbrandenburg** [comment]
Yeah, I'll take it, I have a number of blocked issues at the moment so I could use another.

**Comment by ryanbrandenburg** [comment]
Unfortunately the original plan I had in mind for this (Using the same patern as MVC functional tests) turned out to not actually be possible because of what we're trying to accomplish here (testing things on CoreCLR and CLR, x64 and (hypothetically in the future) x86). My alternate attempt at cleaning it up turned out to not be a big enough improvement to be worth the code churn.

I think these tests are about as clean as I can make them unless we're willing/able to move some or all tests from [this](https://github.com/aspnet/Entropy/blob/dev/test/FunctionalTests/ConfigTests/ConfigSettingObjectWebTests.cs#L48) style to [this](https://github.com/aspnet/Entropy/blob/dev/test/FunctionalTests/MvcTests/LocalizationSampleTest.cs#L15) style, loosing the coverage of CoreCLR vs CLR and Kestrel vs WebListener. I assume the answer on that one is no?

**Comment by muratg** [comment]
@ryanbrandenburg backlogging for now. We can revisit the ideas in the future, especially if there're concerns about adding more tests or stability issues.
