### ISSUE TITLE
Problem with Mvc.RenderViewToString and Url.Action

### ISSUE THREAD

**Issue by Bartmax** [aspnet/Entropy#163]
Using the code from the samples, if I try to use an anchor tag helper on my razor view I get:

```
An unhandled exception occurred while processing the request.

ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
ThrowArgumentOutOfRangeException
```

Same if I try to use `Url.Action`

any idea how to overcome this limitation? thanks.

**Comment by muratg** [comment]
@Eilon Could you triage/assign?

**Comment by ajaybhargavb** [comment]
@Bartmax, this is not a limitation. This is expected. This sample was added to demonstrate rendering a view to a string given a model. It does not involve any controllers or actions. This isn't meant for that. Both Url.Action() and AnchorTagHelper need actions and controllers to be present. So you can't use them here.

**Comment by Bartmax** [comment]
I understand, thanks for your explanation.

I'm using this to create email html from models. In the same project I do have controllers and actions, that's why I want to use something like `<a asp-controller="Home" asp-action="Help">help</a>` but I also need them to be absolute not relative; `//domain.com/Help` instead of `/Help`.

Is there any sample that shows how to make it work with controller/actions or any guidance on what must be done/added ?

currently I'm doing logic on the ViewModel to get the url, maybe that's a reasonable way to do it ?

**Comment by ajaybhargavb** [comment]
Currently there is no way of doing this if you need all the routing behavior to go with it. Since you have your own logic of url generation, you can just write your own implementations of `IUrlHelperFactory` and `IUrlHelper` and add it to services. You will get no routing magic there. You'll need to put your logic in the `Action` method, something like,

```c#
public class CustomUrlHelper : IUrlHelper
{
    public string Action(UrlActionContext actionContext)
    {
        return $"{actionContext.Protocol}://{actionContext.Host}/{actionContext.Controller}/{actionContext.Action}";
    }
    .
    .
    .
}
```
And just add `services.AddSingleton<IUrlHelperFactory, CustomUrlHelperFactory>();` in `Program.cs`
