### ISSUE TITLE
Modify RenderViewToString sample to show how it could be used to process a view concurrently

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Entropy#167]
Based on https://github.com/aspnet/Mvc/issues/5106. Seems like a scenario for users. We should expand the sample to show how to concurrently render views.

**Comment by muratg** [comment]
@Eilon Could you triage/assign this one?

**Comment by pranavkm** [comment]
Fixed in https://github.com/aspnet/Entropy/commit/08304ff82087e112f52015e507553f2531535329
