### ISSUE TITLE
Unable to build Entropy/samples/Localization.StarterWeb

### ISSUE THREAD

**Issue by markjritchie** [aspnet/Entropy#171]
When I try to build the sample it fails due to the dotnet restore failing.

As far as I can see there are too issues: 
- Microsoft.AspNetCore.Mvc": "1.1.0-*

The .\* causes a known exception in VisualStudio, but I don't see anything in the wiki or readme to help people with this issue

The second thing is that its looking for a 1.1.0 version of a package that is at 1.0.1 on [nuget](https://www.nuget.org/packages/Microsoft.AspNetCore.Mvc/):

Again no explanation, please remember that these samples are supposed to be helping people migrate to .NET core so a little guidance would be nice

**Comment by ariesdane** [comment]
The 1.1.* libraries aren't yet public on GitHub. You'll need to update your NuGet package sources to include a reference to the CI builds

`https://dotnet.myget.org/F/aspnetcore-ci-dev/api/v3/index.json`

**Comment by JunTaoLuo** [comment]
Looks like there's nothing here that requires fixes.
