### ISSUE TITLE
File Logger Provider

### ISSUE THREAD

**Issue by hishamco** [aspnet/Entropy#185]
@Eilon Can I make a PR for `FileLoggerProvider` as a show case of the extensible points of the logging system in ASP.NET Core?

**Comment by Eilon** [comment]
@hishamco what would the sample show? I believe we currently recommend that people use a more full-featured production-quality logger such as Serilog, which has many sinks, including one for files. I'm afraid that if we put a minimalistic sample here that might lead people to start using that in production, which is probably a Very Bad Thing™️.

**Comment by hishamco** [comment]
I got you, AFAIK this repo is a chaotic experimental playground for new features and ideas, I just wanna show how to log into files using FileSystem APIs which is something common that the logging repo doesn't support it out-of-the-box, also there's another scenarios to log into the database like DNN, these just few examples. Regarding Serilog I didn't dig into it, because me as developer I'm checking what's available in ASP.NET Core and what isn't, so that's why I open this issue
