### ISSUE TITLE
Can't run Localization.StarterWeb on *nix

### ISSUE THREAD

**Issue by vlad0** [aspnet/Entropy#204]
Localization.StartrWeb.csproj

```xml
 <PropertyGroup>
    <IsPackable>false</IsPackable>
    <TargetFrameworks>net451;netcoreapp1.1</TargetFrameworks>
    <UserSecretsId>aspnet5-Localization.StarterWeb-4772c50f-56f3-4058-bd61-75f1352aeca7</UserSecretsId>
  </PropertyGroup>
```

Got the following error:

> /sdk/1.0.0-rc3-004530/Sdks/Microsoft.NET.Sdk/build/Microsoft.NET.RuntimeIdentifierInference.targets(49,5): error : RuntimeIden
tifier must be set for .NETFramework executables. Consider RuntimeIdentifier=win7-x86 or RuntimeIdentifier=win7-x64. [/Entrop
y/samples/Localization.StarterWeb/Localization.StarterWeb.csproj]
The build failed. Please fix the build errors and run again.

When I add the RuntimeIdentifier in the .csproj file:

```xml
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <TargetFrameworks>net451;netcoreapp1.1</TargetFrameworks>
    <RuntimeIdentifier>win7-x64</RuntimeIdentifier>
    <UserSecretsId>aspnet5-Localization.StarterWeb-4772c50f-56f3-4058-bd61-75f1352aeca7</UserSecretsId>
  </PropertyGroup>
```

I got this error:

>/sdk/1.0.0-rc3-004530/Microsoft.Common.CurrentVersion.targets(1110,5): error MSB3644: The reference assemblies for framework "
.NETFramework,Version=v4.5.1" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your applicat
ion to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assem
bly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend
. [/Entropy/samples/Localization.StarterWeb/Localization.StarterWeb.csproj]
/sdk/1.0.0-rc3-004530/Sdks/Microsoft.NET.Sdk/build/Microsoft.NET.Sdk.targets(76,5): error : Assets file '/Entropy/samples/Localization.StarterWeb/obj/project.assets.json' doesn't have a target for '.NETFramework,Version=v4.5.1/win7-x64'. Ensure you ha
ve restored this project for TargetFramework='net451' and RuntimeIdentifier='win7-x64'. [/Entropy/samples/Localization.Starte
rWeb/Localization.StarterWeb.csproj]
The build failed. Please fix the build errors and run again.

When I remove the .Net451 target framework

```xml
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <TargetFrameworks>netcoreapp1.1</TargetFrameworks>
    <UserSecretsId>aspnet5-Localization.StarterWeb-4772c50f-56f3-4058-bd61-75f1352aeca7</UserSecretsId>
  </PropertyGroup>
```

I got this error:
> Unable to run your project.
Please ensure you have a runnable project type and ensure 'dotnet run' supports this project.
The current OutputType is 'Exe'.

**Comment by JunTaoLuo** [comment]
@vlad0 you don't need to modify the .csproj file. Since the sample targets multiple TFMs, you'll need to specify the one you want to run. For example, this sample will run when you issue the command `dotnet run --framework netcoreapp1.1`
