### ISSUE TITLE
Investigate flaky AppVeyor and Travis builds

### ISSUE THREAD

**Issue by mikeharder** [aspnet/Entropy#241]
The AppVeyor and Travis builds of Entropy have many failures and appear to be flaky:

https://ci.appveyor.com/project/aspnetci/Entropy/history
https://travis-ci.org/aspnet/Entropy/builds

**Comment by ryanbrandenburg** [comment]
The only failures on entropy in the last ~2 months have been real problems. Closing this, we can re-open if we find new instances.
