### ISSUE TITLE
Unit test RazorViewToStringRenderer

### ISSUE THREAD

**Issue by Liero** [aspnet/Entropy#276]
I'm trying to create test project for project based on sample [Mcs.RenderViewToString](https://github.com/aspnet/Entropy/tree/dev/samples/Mvc.RenderViewToString)

I've changed build action to "Embedded Resource" for *.cshtml and used `EmbeddedFileProvider`:

var embeddedProvider = new EmbeddedFileProvider(typeof(Program).Assembly); 
var compositeProvider = new CompositeFileProvider(embeddedProvider);
services.AddSingleton(compositeProvider);

It works fine when I run the project, but the razor views won't compile when I call the RazorViewToStringRenderer from unit test project, see https://stackoverflow.com/questions/49408772/how-to-compile-razor-views-in-unit-test-project

Could you please extend the sample with unit test project? I thing unit testing razor views might be useful for CI.

The test method looks like this:

```csharp
var services = new ServiceCollection();
var applicationEnvironment = PlatformServices.Default.Application;
services.AddSingleton(applicationEnvironment);
services.AddSingleton<IHostingEnvironment>(new HostingEnvironment
{
    WebRootFileProvider = new PhysicalFileProvider(applicationEnvironment.ApplicationBasePath),
    ApplicationName = Path.GetFileName(applicationEnvironment.ApplicationBasePath)
});
var diagnosticSource = new DiagnosticListener("Microsoft.AspNetCore");
services.AddSingleton<DiagnosticSource>(diagnosticSource);
services.AddSingleton<ObjectPoolProvider, DefaultObjectPoolProvider>();
services.AddLogging();
var embeddedProvider = new EmbeddedFileProvider(typeof(Startup).Assembly); //needed for mailtemplates
var compositeProvider = new CompositeFileProvider(embeddedProvider);
services.AddSingleton(compositeProvider);
services.AddMvc().AddRazorOptions(options => options.FileProviders.Add(compositeProvider));
services.AddTransient<IRazorViewToStringRenderer, RazorViewToStringRenderer>();
serviceProvider = services.BuildServiceProvider();

var helper = serviceProvider.GetRequiredService<RazorViewToStringRenderer>();
var model = new EmailViewModel
{
    UserName = "User",
    SenderName = "Sender",
    UserData1 = 1,
    UserData2 = 2
};

helper.RenderViewToStringAsync("~/Views/EmailTemplate.cshtml", model);
```

**Comment by Eilon** [comment]
@Liero the samples here are mostly just random bits of interesting code that the team has written. They are not official samples, so we don't spend a lot of time on them. However, if you do figure out how to get that scenario working and send an update in a pull request to this repo, we would certainly consider it.
