### ISSUE TITLE
Mvc.CustomRoutingConvention is broken

### ISSUE THREAD

**Issue by victorhurdugaci** [aspnet/Entropy#77]
Upon startup:

```
System.TypeLoadException: Method 'get_Configuration' in type 'Microsoft.AspNet.H
osting.HostingEnvironment' from assembly 'Microsoft.AspNet.Hosting, Version=1.0.
0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' does not have an implemen
tation.
   at Microsoft.AspNet.Hosting.WebHostBuilder..ctor(IConfiguration config, Boole
an captureStartupErrors)
   at Microsoft.AspNet.Hosting.WebApplication.Run(Type startupType, String[] arg
s)
   at Microsoft.AspNet.Hosting.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly,
 String[] args, IServiceProvider serviceProvider)
   at Microsoft.Dnx.ApplicationHost.Program.<>c__DisplayClass3_0.<ExecuteMain>b_
_0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```

**Comment by Eilon** [comment]
@ryanbrandenburg could you take a look at this and make sure the sample still works? Then see if @victorhurdugaci can point you at how to add some kind of basic test for it.

**Comment by sky-code** [comment]
I have same problem, please see this example https://github.com/sky-code/HostingSample
It's a default new project, i made changes only in project.json
Here problem in dependencies
but what dependency causes a problem? How to fix it? Error output doesn't have any details

**Comment by sky-code** [comment]
Problem here in EntityFramework.Core and EntityFramework.Commands, if we change versions to 7.0.0-rc1-final hosting will start without errors.
Consider opportunity to add a detailed exception for this kind of errors

**Comment by ryanbrandenburg** [comment]
The problem here appears to be in the project.json:
```
"dependencies": {
    "Microsoft.AspNet.Mvc": "6.0.0-*",
    "Microsoft.AspNet.Server.IIS": "1.0.0-*"
},
"commands": {
    "web": "Microsoft.AspNet.Hosting --server Microsoft.AspNet.Server.WebListener --server.urls http://localhost:5000"
},
```

Basically it looks to me like we're trying to use Microsoft.AspNet.Hosting and Microsoft.AspNet.Server.WebListener without having them as dependencies, and instead of telling us that right off the bat we get an error at the first time we try to use one of them.

It works just fine if I turn the above into:
```
"dependencies": {
    "Microsoft.AspNet.Mvc": "6.0.0-*",
    "Microsoft.AspNet.Hosting": "1.0.0-*",
    "Microsoft.AspNet.Server.WebListener": "1.0.0-*"
},
"commands": {
    "web": "Microsoft.AspNet.Hosting --server Microsoft.AspNet.Server.WebListener --server.urls http://localhost:5000"
},
```

@victorhurdugaci does that jive with everything you saw?

If I'm right here I would say the fix would be to complain earlier, when we can't find the assembly we're looking for.
