### ISSUE TITLE
Remove Config.ChangeNotification.Web

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/Entropy#82]
This sample is currently empty except for a `project.json` file which has only two dependencies. Seems like it was never actually written?

**Comment by muratg** [comment]
@divega?

**Comment by muratg** [comment]
@divega Please feel free to bring it back if we need a sample for this, or remove this sample all together. Putting it in backlog to take it out of triage for now.

**Comment by Eilon** [comment]
Let's delete `Config.ChangeNotification.Web`.

@JunTaoLuo can you do the honors?
