### ISSUE TITLE
RenderViewToString : viewLocationBasePath is irrevelant

### ISSUE THREAD

**Issue by adrien-constant** [aspnet/Entropy#92]
First thanks for sharing.

The following code is useless / does not work as expected.

` WebRootFileProvider = new PhysicalFileProvider(viewLocationBasePath ?? applicationEnvironment.ApplicationBasePath)`

The web root is used when looking for static files, aka the wwwroot folder (as described in the source code comments).
It is not used for razor views lookup.
Thus, setting the parameter does not work if the views directory is outside the project directory, which what I try to achieve.

**Comment by Eilon** [comment]
@ajaybhargavb any thoughts on this?

**Comment by ajaybhargavb** [comment]
Thanks for reporting this. I checked and it does look like it is ignored when the views directory is outside the project directory. I'll investigate more and work on a fix.

**Comment by ajaybhargavb** [comment]
Make sure to set the `customApplicationBasePath` here https://github.com/aspnet/Entropy/blob/dev/samples/Mvc.RenderViewToString/Program.cs#L21 to the folder that contains `Views` folder and not the `Views` folder itself.

**Comment by adrien-constant** [comment]
Thanks a lot, that works with files outside the project directory now.

Just a quick note for those who may have Razor template compilation errors : the file _ViewImports.cshtml is loaded from the `customApplicationBasePath ` directory, so you may have to add the corresponding references to your project (tag helpers, etc)
