### ISSUE TITLE
Move app.UseRequestLocalization after UseExceptionHandler

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Entropy#99]
@hishamco should app.UseRequestLocalization be moved after adding an exception handler on the chance you get an exception in loc? I assume it's OK to have it before Auth, given that Auth will eventually run.

**Comment by hishamco** [comment]
I didn't run on such scenario, are you facing issue when you move it after ```UseExceptionHandler```?!! if it's so provide me a link to a repo that reproduce this issue

**Comment by Rick-Anderson** [comment]
No, I've actually tried to force an exception to test this and haven't been able to. That doesn't mean someone won't hit an exception in loc and not get a good error message (because they are adding loc before exceptions). 

I'm using Entropy  to write my loc document and I'm talking about where to add UseRequestLocalization. Can I email you a copy of the article to review? If so, what contact info? You can email me Rick.Anderson[at]microsoft[dot]com

**Comment by hishamco** [comment]
Can you send the link here or attach the code or create a repo if you don't mind. This is better that private emails while we are in OSS world :smile: also anyone can participate here

**Comment by Rick-Anderson** [comment]
I moved  
` var locOptions = app.ApplicationServices.GetService<IOptions<RequestLocalizationOptions>>();
  app.UseRequestLocalization(locOptions.Value);`

after the exception handler is set and it works fine. I think I'll keep it that way for my sample.

I'll send you a link to my preview loc document in a couple days.

**Comment by hishamco** [comment]
Using ```app.UseRequestLocalization```  in ```Configure``` method before ```app.UseExceptionHandler``` should work fine. Either you supply the localization options in the ```Configure``` or ```ConfigureServices``` method
